### ISSUE TITLE
Please remove unnecessary files

### ISSUE THREAD

**Issue by pcav** [muratkendir/FilterLayersAtOnce#1]
.pyc etc.
They are generated automatically during installation.
Thanks.

**Comment by muratkendir** [comment]
It is my first plugin,

I removed unnecessary files from zip file, but i didn't know all files if
they are necessary or not. Can you please help a bit?

I will upload plugin again.

**Comment by pcav** [comment]
as mentioned, compiled files (.pyc and html) are generated upon installation, so they do not belong to the repo (nor the zipfile).
feel free to upload a new version.
cheers

**Comment by muratkendir** [comment]
i noticed following error:


*duplicate key value violates unique constraint "plugins_plugin_name_key"
DETAIL: Key (name)=(FilterLayersAtOnce) already exists. *

Can you please delete previously uploaded plugin
*?*

**Comment by pcav** [comment]
you should add a new version to the same repo, not a new duplicated repo

**Comment by muratkendir** [comment]
Aha, thank you...

I guess i did it.

**Comment by pcav** [comment]
I can no longer find it

**Comment by pcav** [comment]
pycache still present in the repo

**Comment by muratkendir** [comment]
I uploaded again as 0.3 version with following index. Is it ok?

[image: 2020-02-17 17_38_53-FilterLayersAtOnce-master.zip.png]

**Comment by pcav** [comment]
https://github.com/muratkendir/FilterLayersAtOnce/tree/master/__pycache__

**Comment by muratkendir** [comment]
Sorry for that, i was thinking you mean QGIS plugin share repository... I removed scripts, _py_cache and test folders from plugin repository and test it, its working.

**Comment by pcav** [comment]
Thanks
